networks:
  common:
    driver: bridge

services:
  # flutter_engine:
  #   platform: linux/i386
  #   privileged: true
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   restart: no
  #   tty: true
  #   networks: [ common ]
  #   working_dir: /src
  #   volumes:
  #     - ./:/src:rw
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   ulimits:
  #     nofile:
  #       soft: 655350
  #       hard: 655350
  flutter_engine_x64:
    platform: linux/amd64/v3
    privileged: true
    user: builder
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: no
    tty: true
    networks: [ common ]
    working_dir: /src
    volumes:
      - ./:/src:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ulimits:
      nofile:
        soft: 655350
        hard: 655350
  # flutter_engine_armv7:
  #   platform: linux/arm/v7
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   restart: unless-stopped
  #   tty: true
  #   networks: [ common ]
  #   working_dir: /src
  #   volumes:
  #     - ./:/src:rw
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   ulimits:
  #     nofile:
  #       soft: 655350
  #       hard: 655350
  # desktop_armv7:
  #   platform: linux/arm/v7
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile.desktop
  #   restart: unless-stopped
  #   tty: true
  #   networks: [ common ]
  #   working_dir: /src
  #   volumes:
  #     - ./:/src:rw
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   ulimits:
  #     nofile:
  #       soft: 655350
  #       hard: 655350
